FROM python:3.11-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY krav.txt .
RUN pip install --no-cache-dir -r krav.txt

COPY . .

CMD ["python", "hoved.py"]
